security:
    acl:
        connection: default

    role_hierarchy:
        ROLE_MODERATOR:   [ROLE_USER]
        ROLE_ADMIN:       [ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: user, roles: [ 'ROLE_USER' ] }
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }
                    superadmin: { password: superadmin, roles: [ 'ROLE_SUPER_ADMIN' ] }
        database:
            entity:
                class:    AppBundle\Entity\User
                property: username

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User: plaintext

    firewalls:

        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider:  database
            form_login:
                login_path: security_login
                check_path: security_login_check
                default_target_path: /
                always_use_default_target_path: true
            logout:
                path:   security_logout
                target: /

    access_control:
            - { path: ^/(_(profiler|wdt)|css|images|js)/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, role: IS_AUTHENTICATED_REMEMBERED }

